# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: zhouzhuojie/flagr-ci
    working_directory: /go/src/github.com/checkr/flagr
    steps:
      - checkout
      - run: make test
      - run: cd browser/flagr-ui && yarn install && yarn run test
